/**
 * English term popovers, by the same ids as terms.js. Same rules: one or two plain sentences, no second
 * unexplained term inside; longer explanations belong on the Glossary page.
 */
export const termsEn = {
  chunk: { title: 'Chunk', body: 'A piece of a document. The search finds these pieces, not whole documents. The model gets only the few pieces the search picks.' },
  embedding: { title: 'Embedding', body: 'Text turned into a list of numbers (a vector). Texts with close meanings get close numbers.' },
  vektor: { title: 'Vector', body: 'An ordered list of numbers. Our embedding model makes a vector of 1024 numbers for each text.' },
  cosine: { title: 'Cosine similarity', body: 'How much two vectors point the same way. It runs from −1 to 1. A score of 1 means the same direction, so the same meaning. In our model, even unrelated texts score far above 0. Our unrelated pair scored 0.503. Compare a score with other scores. One score alone tells you little.' },
  topk: { title: 'Top-k', body: 'The k closest chunks the search returns. Here, k = 5. If k is small, the right chunk can be left out of the list. If k is large, rerank scores more chunks and takes longer. The prompt still gets only the best 3.' },
  rerank: { title: 'Rerank', body: 'Sorting the search results again with a second, more careful model. It reads the question and the chunk together.' },
  metadata: { title: 'Metadata', body: 'The labels on a chunk, other than its text. They say which document, which edition and who can read it. The search uses them as filters.' },
  vectordb: { title: 'Vector DB', body: 'A database that stores vectors, texts and metadata. It finds the closest vectors fast. Ours is Chroma.' },
  hnsw: { title: 'HNSW', body: 'A way to organize vectors so search is fast. Each vector links to its nearest neighbors. A search follows these links, so it checks only the nearby vectors.' },
  token: { title: 'Token', body: 'The smallest piece of text a model reads and writes. Often a token is part of a word. Cost and limits are counted in tokens.' },
  context: { title: 'Context window', body: 'The limit on how many tokens a model can read at one time. The prompt, the sources and the answer must all fit in it.' },
  abstain: { title: 'Abstain', body: 'The model says “I don’t know” on purpose when the answer isn’t in the sources. This doesn’t happen by itself. You have to design it.' },
  injection: { title: 'Prompt injection', body: 'Hiding an instruction inside a text the model reads. In RAG, that text can be a document.' },
  finetune: { title: 'Fine-tuning', body: 'Training an existing model a little more with your own examples. It changes the numbers inside the model (its weights). It teaches behavior well: tone, format, terms. It is not reliable for facts. To change what it learned, you train again.' },
  weights: { title: 'Weights', body: 'The billions of numbers a model learns in training. The model keeps what it knows in these numbers. When training ends, they stop changing.' },
  pca: { title: 'PCA', body: 'Bringing 1024 dimensions down to 2, so we can draw them. It finds the two directions where the chunks differ most. Most of the information is lost, but the rough layout stays.' },
  mrr: { title: 'MRR', body: 'For each question, take 1 divided by the rank of the first right result. Then average this over all questions. A score of 1.0 means the right result is always first.' },
  hallucination: { title: 'Hallucination', body: 'The model invents an answer and states it with full confidence, like a fact.' },
  goldset: { title: 'Gold set', body: 'A list of questions with known answers. Each question has the right section and the expected value. We score every version of the system with the same list.' },
  hit1: { title: 'hit@1', body: 'Is the first result right? 1 if yes, 0 if no. Then we take the average over all questions.' },
  recallk: { title: 'recall@k', body: 'How many of the right sections get into the top k results. It ignores the rank. Being in the list is enough.' },
  judge: { title: 'LLM-as-judge', body: 'Asking another language model to score an answer. For example: “Is every claim in this answer in the sources?” The judge can be wrong, so we measure the judge too.' },
  hybrid: { title: 'Hybrid search', body: 'Keyword search combined with vector search. It helps with words you search for exactly, like codes, numbers and names.' },
  hyde: { title: 'HyDE', body: 'The model first writes an imagined answer to the question. Then we search with that answer, not with the question. An imagined answer sounds more like the documents than the question does.' },
  parentchild: { title: 'Parent-child', body: 'Search with small chunks. Then give the model the bigger chunk around each one. Small chunks are easy to find. Big chunks are easy to read.' },
  agentic: { title: 'Agentic RAG', body: 'RAG where the model runs the search. It splits the question and searches for each part. It repeats until it has enough information. It makes more model calls, so it takes more time.' },
  graphrag: { title: 'GraphRAG', body: 'GraphRAG lists the things in the documents (people, products, places) and how they link. At question time, it follows those links. It helps when the answer sits in the links between documents.' },
  multiquery: { title: 'Multi-query', body: 'The model rewrites one question in a few different ways. Each version gets its own search. Then we merge the results.' },
  ragfusion: { title: 'RAG-fusion', body: 'It works like multi-query, but it merges the result lists by rank. A chunk near the top of several lists moves to the front.' },
  pii: { title: 'Personal data (PII)', body: 'Information that identifies a person: name, employee number, phone, email. Hide it (mask it) when a document enters the system, before it becomes a vector.' },
  rag: { title: 'RAG', body: 'Retrieval-Augmented Generation. Before the model answers, we find the relevant chunks and give them to the model. The model doesn’t change. Only its input changes.' },
  ingest: { title: 'Ingest', body: 'The preparation that makes documents searchable: load, clean, split, turn into vectors, store. It runs once, and again when a document changes.' },
  prompt: { title: 'Prompt', body: 'The full text the model gets. In RAG, it holds the rules, the numbered sources and the question. The model sees nothing else.' },
  bruteforce: { title: 'Brute force', body: 'Comparing the question with every vector in the store, one by one. The result is exact, but the work grows with the number of vectors.' },
  ann: { title: 'ANN', body: 'Approximate nearest neighbor search. It finds close vectors without checking all of them. It jumps from neighbor to neighbor inside an index. This is fast. It usually finds the closest vector, but there is no guarantee.' },
  mmr: { title: 'MMR', body: 'Maximal Marginal Relevance. MMR picks results one by one. Each pick must be close to the question and different from the picks before it. You get varied chunks, not copies.' },
};
