/**
 * English term popovers, by the same ids as terms.js. Same rules: one or two plain sentences, no second
 * unexplained term inside; longer explanations belong on the Glossary page.
 */
export const termsEn = {
  chunk: { title: 'Chunk', body: 'A piece of a document. The search finds these pieces, not whole documents. The model gets only the few pieces the search picks.' },
  embedding: { title: 'Embedding', body: 'A text turned into a list of numbers (a vector). Texts with close meanings get close numbers.' },
  vektor: { title: 'Vector', body: 'An ordered list of numbers. Our embedding model makes a vector of 1024 numbers for each text.' },
  cosine: { title: 'Cosine similarity', body: 'How much two vectors point the same way. It runs from −1 to 1, and 1 means the same direction (the same meaning). In our model, even unrelated texts don’t get near 0. Our unrelated pair scored 0.503. A score only means something next to other scores.' },
  topk: { title: 'Top-k', body: 'The k closest chunks the search returns. Here, k = 5. If k is small, the right chunk can miss the list. If k is large, rerank scores more chunks and takes longer. The prompt still gets only the best 3.' },
  rerank: { title: 'Rerank', body: 'Sorting the search results again with a second, more careful model. It reads the question and the chunk together.' },
  metadata: { title: 'Metadata', body: 'The labels on a chunk, apart from its text. They say which document, which edition and who may read it. The search uses them as filters.' },
  vectordb: { title: 'Vector DB', body: 'A database that stores vectors, texts and metadata. It finds the closest vectors fast. Ours is Chroma.' },
  hnsw: { title: 'HNSW', body: 'An index that many vector DBs use. It links each vector to its neighbors in a graph. A search visits only the nearby part of the graph.' },
  token: { title: 'Token', body: 'The smallest piece of text a model reads and writes. It is roughly part of a word. Cost and limits are counted in tokens.' },
  context: { title: 'Context window', body: 'The most tokens a model can read at one time. The prompt, the sources and the answer must all fit in it.' },
  abstain: { title: 'Abstain', body: 'The model says “I don’t know” on purpose when the answer isn’t in the sources. This doesn’t happen by itself. You have to design it.' },
  injection: { title: 'Prompt injection', body: 'Hiding an instruction inside a text the model reads. In RAG, that text can be a document.' },
  finetune: { title: 'Fine-tuning', body: 'Training a ready model a little more with your own examples. It changes the model’s weights. It teaches behavior well: tone, format, terms. It is not reliable for facts. To change what it learned, you train again.' },
  weights: { title: 'Weights', body: 'The billions of numbers a model learns in training. The model keeps what it knows here. When training ends, they freeze.' },
  pca: { title: 'PCA', body: 'Bringing 1024 dimensions down to 2, so we can draw them. It finds the two directions where the chunks differ most. Most of the information is lost, but the rough layout stays.' },
  mrr: { title: 'MRR', body: 'For each question, 1 / (rank of the first right result). Then the average over all questions. 1.0 means the right result is always first.' },
  hallucination: { title: 'Hallucination', body: 'The model makes something up and says it with confidence, like a fact.' },
  goldset: { title: 'Gold set', body: 'A list of questions with known answers. Each question has the right section and the expected value. We score every version of the system with the same list.' },
  hit1: { title: 'hit@1', body: 'Is the first result right? 1 if yes, 0 if no. Then we take the average over all questions.' },
  recallk: { title: 'recall@k', body: 'How many of the right sections get into the top k results. It ignores the rank. Being in the list is enough.' },
  judge: { title: 'LLM-as-judge', body: 'Asking another language model to score an answer. For example: “Is every claim in this answer in the sources?” The judge can be wrong too, so you measure it as well.' },
  hybrid: { title: 'Hybrid search', body: 'Keyword search combined with vector search. It helps with words you search for exactly, like codes, numbers and names.' },
  hyde: { title: 'HyDE', body: 'The model first writes an imagined answer to the question. Then we search with that answer, not with the question. An imagined answer sounds more like the documents than the question does.' },
  parentchild: { title: 'Parent-child', body: 'Search with small chunks. Then give the model the bigger chunk around each one. Small chunks are easy to find. Big chunks are easy to read.' },
  agentic: { title: 'Agentic RAG', body: 'RAG where the model runs the search. It splits the question and searches for each part. It repeats until it has enough information. More calls, more time.' },
  graphrag: { title: 'GraphRAG', body: 'It builds a graph of the things in the documents and their links. At question time, it follows those links. It helps when the answer is in the links between documents.' },
  multiquery: { title: 'Multi-query', body: 'The model rewrites one question in a few different ways. Each version gets its own search. Then we merge the results.' },
  ragfusion: { title: 'RAG-fusion', body: 'It works like multi-query, but it merges the result lists by rank. A chunk near the top of several lists moves to the front.' },
  pii: { title: 'Personal data (PII)', body: 'Information that identifies a person: name, employee number, phone, email. Mask it when a document enters the system, before it becomes a vector.' },
  rag: { title: 'RAG', body: 'Retrieval-Augmented Generation. Before the model answers, we find the relevant chunks. We put them in front of the model. The model doesn’t change. Only its input changes.' },
  ingest: { title: 'Ingest', body: 'The preparation that makes documents searchable: load, clean, split, turn into vectors, store. It runs once, and again when a document changes.' },
  prompt: { title: 'Prompt', body: 'The full text the model gets. In RAG, it holds the rules, the numbered sources and the question. The model sees nothing else.' },
  bruteforce: { title: 'Brute force', body: 'Comparing the question with every vector in the store, one by one. The result is exact, but the work grows with the number of vectors.' },
  ann: { title: 'ANN', body: 'Approximate nearest neighbor. It finds the closest vectors without checking them all. It jumps from neighbor to neighbor inside an index. It is fast. It usually finds the closest one, but there’s no guarantee.' },
  mmr: { title: 'MMR (Maximal Marginal Relevance)', body: 'MMR picks results one by one. Each pick must be close to the question and different from the picks before it. You get varied chunks, not copies.' },
};
